### ISSUE TITLE
Issue with conflicting peer dependencies in sanity-plugin-media on React 18

### ISSUE THREAD

**Issue by sadhikari1r** [sanity-io/sanity-plugin-media#147]
I'm facing an issue with the sanity-plugin-media package while installing it in my project. I'm getting the following warning:

```
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17" from react-hook-form@6.15.8
npm WARN node_modules/sanity-plugin-media/node_modules/react-hook-form
npm WARN   react-hook-form@"^6.15.1" from sanity-plugin-media@2.0.5
npm WARN   node_modules/sanity-plugin-media
npm WARN   1 more (@hookform/resolvers)
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17" from react-hook-form@6.15.8
npm WARN   node_modules/sanity-plugin-media/node_modules/react-hook-form
npm WARN     react-hook-form@"^6.15.1" from sanity-plugin-media@2.0.5
npm WARN     node_modules/sanity-plugin-media
npm WARN     1 more (@hookform/resolvers)

```

The issue is because the dependency of sanity-plugin-media is still using "@hookform/resolvers": "2.0.0-beta.3" and "react-hook-form": "^6.15.1", which causes conflicts with the peer dependency of react@17.0.2.

I noticed that there are already two pull requests for this issue:
https://github.com/sanity-io/sanity-plugin-media/issues/58
https://github.com/sanity-io/sanity-plugin-media/issues/124

However, both of them have not been updated for a long time. There is also an existing pull request that addresses this issue, but it has not been merged yet:
https://github.com/sanity-io/sanity-plugin-media/pull/136
https://github.com/sanity-io/sanity-plugin-media/pull/96

Can someone please take a look and update the pull request or provide an alternative solution to resolve this issue? 

Thank you.

**Comment by robinpyon** [comment]
Thanks for flagging @sadhikari1r!

This should be fixed in `2.1.1`, which now uses an updated version of react-hook-form and no longer yields peer dependency warnings on install.
