### ISSUE TITLE
"Upload images" and "Media" buttons are unresponsive in Safari

### ISSUE THREAD

**Issue by eivindml** [sanity-io/sanity-plugin-media#158]
**Describe the bug**

Pressing either of the buttons "Upload Images" or "Media", in Safari browser does nothing. When testing the excact same studio in Chrome, the media browser is opened. So pretty sure this is a Safari spesific bug.

<img width="699" alt="Skjermbilde 2023-06-06 kl  10 59 29" src="https://github.com/sanity-io/sanity-plugin-media/assets/202450/d288a016-0f28-4f58-9934-36d636408886">

**To Reproduce**
1. Open any studio with the plugin in Safari on macOS
2. Try to select an image asset and see nothing happens

**Expected behavior**
Media browser should open.

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: Safari 16.4

**Comment by eivindml** [comment]
We are two people so far that have the same issue.

**Comment by robinpyon** [comment]
Thanks @eivindml, apologies for the latency here

Are you still seeing this issue? If so, are you able to specify which version of the plugin you're using?

This is especially curious as you're not seeing anything when pressing the **Uploaded Images** button, which _should_ open the Studio's default asset picker. This to me indicates that the issue may potentially lie outside of this plugin.

**Comment by eivindml** [comment]
I've just now had time to test it, and I can't seem to reproduce it. 🥳 So looks good to me.
