### ISSUE TITLE
Multiple filters of the same type blocked in v3

### ISSUE THREAD

**Issue by peterjreynoldsii** [sanity-io/sanity-plugin-media#165]
**Describe the bug**
In v3, you can no longer add multiple filters of the same type, when in v2, you could. 

**To Reproduce**
1. Go to media browser
2. Click on filters
3. add a filter of any given type
4. try to add another filter of the same type
5. be unable to click it. 😮 

**Expected behavior**
I would like to be able to dd multiple of the same filter if I want to narrow the scope of my search from a few angles if my media is complex. 

**Screenshots**
![image](https://github.com/sanity-io/sanity-plugin-media/assets/39418872/a2534e46-9392-43be-bc23-aedfa9211a66)

**Desktop (please complete the following information):**
 - OS: Ventura 13.4
 - Browser: Chrome
 - Version: Sanity Studio v3

**Additional context**
Thanks for this super helpful plugin! I will monitor to add more detail to the request if you need it!

**Comment by robinpyon** [comment]
Thanks @peterjreynoldsii – this is now possible as of `2.1.0`. Please shout if you're having issues.
