### ISSUE TITLE
When adding media to a document, popover menus do not appear

### ISSUE THREAD

**Issue by schrockwell** [sanity-io/sanity-plugin-media#167]
**Describe the bug**
When bringing up the media browser to add media to a document, the popover menus (e.g. "Add filter", and sorting) are not visible.

**To Reproduce**
1. In the Desk, go to to a document that has an image field.
2. For the image field, click "Select" -> "Media" to bring up the media browser.
3. Click on the "Add filter" button.
4. Note that the button state changes, but the menu item does not appear.
5. Note that the popover `<div>` does appear in the DOM, but has the `hidden` attribute applied.

**Expected behavior**
The menus should appear.

**Screenshots**
Video: https://github.com/sanity-io/sanity-plugin-media/assets/30214/4e239b84-eccd-4511-8a3b-44cc8f26c8fd

Showing the hidden menu div: 

<img width="546" alt="image" src="https://github.com/sanity-io/sanity-plugin-media/assets/30214/b498843c-a7cf-40b8-9b3d-7d732e69b28c">

**Desktop:**
 - OS: macOS Ventura 13.3.1 (a)
 - Browser: Firefox 
 - Version: 114.0.2

**Additional context**
Possibly related to #82.

Note that bringing up the media browser via the top bar of Sanity Studio works as expected.

My best guess is that the Floating UI library is incorrectly determining the visibility the button, and hence hiding the associated menu... [maybe here](https://github.com/sanity-io/ui/blob/4e2523f1b0c53a84f51dc6ce025d288a5c242599/src/primitives/popover/popover.tsx#L338)

**Comment by robinpyon** [comment]
Thanks for flagging this @schrockwell – this should be resolved as of [2.0.6+](https://github.com/sanity-io/sanity-plugin-media/releases/tag/v2.0.6) – please let us know if you're still having issues here.
