### ISSUE TITLE
Not showing all images compared to uploaded images

### ISSUE THREAD

**Issue by JamesSingleton** [sanity-io/sanity-plugin-media#175]
**Describe the bug**
I have been uploading a lot of images lately and right now I am moving some documents around so I just need to reuse images that are already uploaded. However, when I click on "Media" in the Select dropdown for images, it isn't showing all the images.

**To Reproduce**
1. Create a new document that has an image
2. Select "Uploaded images"
3. Look at all the images
4. Now select "Media"
5. Note there is a discrepancy 

**Expected behavior**

**Screenshots**

## Uploaded Images
![Screenshot 2023-07-15 at 3 34 49 PM](https://github.com/sanity-io/sanity-plugin-media/assets/21000200/e626aa79-8f83-448c-b9e6-e16f2279e052)

## Media
![Screenshot 2023-07-15 at 3 36 09 PM](https://github.com/sanity-io/sanity-plugin-media/assets/21000200/ee0e0178-171e-4eb5-9b29-7c4c06f9ad31)

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 (c) 
 - Browser: Chrome
 - Version: 114.0.5735.198

**Smartphone (please complete the following information):**

N/A

**Additional context**
This is local development, not sure if that plays into it at all. The media plugin used to show everything and then while creating documents and selecting images from media it all of a sudden stopped showing all the images.

**Comment by robinpyon** [comment]
Thanks @JamesSingleton

A few quick questions:
- Which version of the media plugin are you using?
- If you try reduce your browser viewport size and repeat the steps you've outlined, are you able to view remaining images?

It appears you're seeing the first page of results (50 items) only. If I had to hazard a guess – since you're able to view all items entirely within your current viewport size – no overflow scrolling occurs, and as such, no new pages are loaded – which is definitely a bug.

**Comment by JamesSingleton** [comment]
@robinpyon,

To answer your questions:

* `"sanity-plugin-media": "^2.2.1",`
* So this also happens when I select "Media" from the dropdown on a 32" monitor. The second screenshot was just to show that nothing was being loaded. However, I will double check later today and update here.

**Comment by JamesSingleton** [comment]
Ok @robinpyon yes you are correct... If I view the media tab on just my laptop screen it will allow me to scroll through all the images. However, if I put it to a bigger monitor than my 16" laptop screen, then it does not.

**Comment by robinpyon** [comment]
This behaviour appears to [intentional by design](https://github.com/petyosi/react-virtuoso/issues/919) in `react-virtuoso` (which renders the virtualised asset grid).

In the meantime, I've increased the limit from 50 to 100 in `2.2.2` which should hopefully alleviate this issue for you.
