### ISSUE TITLE
Image field crashes when clicking "Select"

### ISSUE THREAD

**Issue by marco-land** [sanity-io/sanity-plugin-media#222]
**Describe the bug**
The image field crashes when hitting the select button
`Error: useToolOptions must be used within an ToolOptionsProvider`

**Screenshots**

**Plugin and environment information:**
![CleanShot 2024-07-16 at 17 54 33](https://github.com/user-attachments/assets/4a9781b8-d420-43f8-9ce1-070dd8bf4c3c)

- sanity-plugin-media v2.3.0
- Sanity v3.51.0
- macOS 14.5 (23F79)
- Chrome Version 126.0.6478.127 (Official Build) (arm64)

**Comment by DavithkbY** [comment]
I have the exact same issue.

**Comment by pavanpodila** [comment]
This was working until a few version back of Sanity Studio ... either some API in the studio changed or this plugin has changed its usage of the API ...

**Comment by marco-land** [comment]
> This was working until a few version back of Sanity Studio ... either some API in the studio changed or this plugin has changed its usage of the API ...

Yes, the bug appears with the most recent update of the media plugin `v2.3.0`. 
Right now, I downgraded the media plugin to `v2.2.5` and it works again, also with the most recent Sanity `v3.51.0`.

**Comment by pavanpodila** [comment]
Oh nice let me try that

**Comment by rylanharper** [comment]
The plugin also crashes when clicking the Media navigation link for on the top bar of the studio..

**Comment by obrassard** [comment]
>Yes, the bug appears with the most recent update of the media plugin v2.3.0.
Right now, I downgraded the media plugin to v2.2.5 and it works again, also with the most recent Sanity v3.51.0.

The latest version of the plugin (v2.3.1) seems to works well if you downgrade Sanity to v3.51.0
It might be an issue with the sanity package itself ?

**Comment by pavanpodila** [comment]
Yup...it throws a different error now for Sanity v3.52.0
![image](https://github.com/user-attachments/assets/3efd58be-6eaf-404c-a20a-b125f970481c)

Downgrading seems like the only option

**Comment by hleomojica** [comment]
I also encountered this issue and was able to resolve it by upgrading to version 2.3.2.  Prior to the upgrade, I was using version 2.3.0.

Sanity: v3.51.0
Node.js : v18.18.0

**Comment by pavanpodila** [comment]
> I also encountered this issue and was able to resolve it by upgrading to version 2.3.2. Prior to the upgrade, I was using version 2.3.0.
> 
> Sanity: v3.51.0 Node.js : v18.18.0

Its still an issue with 
Sanity: 3.52.0
Media: 2.3.2

**Comment by obrassard** [comment]
The new release fixed the issue https://github.com/sanity-io/sanity/releases/tag/v3.52.1

**Comment by marco-land** [comment]
> The new release fixed the issue https://github.com/sanity-io/sanity/releases/tag/v3.52.1

I can confirm everything is running again
```
"sanity": "^3.52.1"
"sanity-plugin-media": "^2.3.2"
```
