### ISSUE TITLE
Feature request: Toggle dark theme

### ISSUE THREAD

**Issue by r3nanp** [sanity-io/sanity-plugin-media#86]
Hi!! I really love this plugin. It would be nice if there is a way to toggle the theme or override the css colors to match the customization of Sanity.

For example: 
[Styling Sanity Studio](https://www.sanity.io/docs/styling)

**Comment by jxhdev** [comment]
+1 to this.

Our team has a lot of media in .PNG format for chemical structures and it is hard to see them with dark theme.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/26941285/197646803-aa87cd3a-4d5a-4ca9-8d6c-cd9d2cbf8c72.png">

**Comment by msichterman** [comment]
+1. Would like the theme to toggle to Light/Dark mode based on what the parent Sanity Studio setting is 🙂

**Comment by robinpyon** [comment]
As of `2.2.2` this plugin should now use colours appropriate to the colour mode in use by the studio. 

This also affects checkerboard backgrounds on transparent images, e.g:

<img width="1364" alt="image" src="https://github.com/sanity-io/sanity-plugin-media/assets/209129/9e264d4b-90ad-4af4-9713-1a2da3d2e26f">
